In [17]:
import pandas as pd      #here importing pandas specialize in datasets
import numpy as np       #import numpy library specialse in math

In [18]:
path = r"C:\Users\ayoub\OneDrive\Desktop\machine learning ai\assigment 7.1\Canada by Citizenship.csv"
df = pd.read_csv(path,skiprows=20,na_values="..")  # import the the path of the dataset and make it in a vaiable called "df"
df.head() #this function make us see the first lines of the dataset and its features
# skiprows=20,na_values=".." means skipp the first 20 rows and dont make in the data framke because its has string and
#it will be null in the data fram

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [19]:
# Drop columns we don't need
df.drop(['Type', 'Coverage', 'AREA', 'REG', 'DEV'], axis=1, inplace=True)
#drop means deleate and we give it colums name we wamt to delete and axis 1 means columns only
#inplace true means make modification on the same dataset df it self , we dont have to assigne another name

# Rename columns
df.rename(columns={
    'OdName'   : 'Country',
    'AreaName' : 'Continent',
    'RegName'  : 'Region'
}, inplace=True)

# here we rename the colums we still have as the same the example we have 

# Set Country as the index
df.set_index('Country', inplace=True)
#in this step we make the column country the label for our data set

#Add Total column 
df['Total'] = df.loc[:, '1980':'2013'].sum(axis=1)
#in this last step we are making a new column "total" and we are adding all number for each country fro 1980 to 2013 
#and make the total fo each country

df.head()  #here we are printing the result

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,15699
Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,15